name: 'Build and upload resulted image to GCP repository'
on:
  pull_request:
    branches:
      - $default-branch
# add more branches here or remove `branches` element to apply to _all_ branches


env:
  PROJECT_ID: ${{ secrets.CI_PROJECT_ID }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  REPOSITORY: ${{ secrets.CI_REPOSITORY_NAME }}


jobs:
  build_artifacts:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    # Github-managed Linux machine (on 28-aug-22 it is ubuntu-20.04)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Establish keyless authentication to Google Cloud using Workload Identity Federation
      - name: 'Authenticate vs Google'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.CI_WIF_PROVIDER }}'
          service_account: '${{ secrets.CI_WIF_SERVICE_ACCOUNT }}'

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: 'Build and Push Artifact(s)'
        